---
openapi: 3.0.0
info:
  title: User Management Api
  description: |
    This is a sample User Management Api
  contact:
    email: vnikabadze@unisens.ge
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/vaskania/User-Management/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /users:
    get:
      tags:
      - User
      description: Get all users
      responses:
        "200":
          description: Get an array of users
          content:
            application/json:
              schema:
                type: array
                example:
                  username: User Name
                  firstName: User
                  lastName: Name
                items:
                  $ref: '#/components/schemas/UsersList'
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: User not found
  /user/register:
    post:
      tags:
      - User
      summary: Create new user
      description: This can only be done with unique username
      responses:
        "201":
          description: New user was created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Signup'
              example:
                message: New user was created successfully
        "400":
          description: Username already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: User already exists
  /user/login:
    post:
      tags:
      - User
      summary: Logs user
      description: The username for login
      responses:
        "200":
          description: logged in successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                message: Logged in successfully
        "400":
          description: Invalid username/password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Invalid username/password
  /user/{id}:
    get:
      summary: Get user by id
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: string
          description: The id that needs to be fetched.
      responses:
        "200":
          description: User profile fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
              example:
                username: Username
                firstName: User
                lastName: Name
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: User not found
    delete:
      tags:
      - user
      description: This can only be done by the logged in user.
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: string
          description: The id that needs to be fetched.
      responses:
        "200":
          description: User profile deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteProfile'
              example:
                message: User with ID:"id" was deleted syccessfully
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: User not found
  /user/update-profile/{id}:
    put:
      tags:
      - User
      summary: Updated user firstName or lastName
      description: This can only be done by the logged in user.
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: string
          description: The id that needs to be fetched.
      responses:
        "200":
          description: Updated user object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateUserProfile'
              example:
                message: Profile updated successfully
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: User not found
  /user/update-password/{id}:
    put:
      tags:
      - User
      summary: Updated user password
      description: This can only be done by the logged in user.
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: string
          description: The id that needs to be fetched.
      responses:
        "200":
          description: Updated user password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateUserPassword'
              example:
                message: Password updated successfully
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: User not found
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
    User:
      required:
      - password
      - username
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        salt:
          type: string
        delete:
          type: boolean
    UsersList:
      type: object
      properties:
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
    Signup:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    UserProfile:
      type: object
      properties:
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
    UpdateUserProfile:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
    UpdateUserPassword:
      type: object
      properties:
        password:
          type: string
    DeleteProfile:
      type: object
      properties:
        id:
          type: string
